/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface IUnixProcess {
  fd: number
  pid: number
  pty: string
}
export interface IUnixOpenProcess {
  master: number
  slave: number
  pty: string
}
export function ptyFork(file: string, args: Array<string>, env: Record<string, string>, cwd: string, cols: number, rows: number, uid: number, gid: number, utf8: boolean, onexit: (...args: any[]) => any): IUnixProcess
export function ptyOpen(cols: number, rows: number): IUnixOpenProcess
export function ptyProcess(fd: number, tty: string): string | undefined | null
/**
 * Resizes the terminal pointed to by the provided file descriptor
 * to the preferred
 */
export function ptyResize(fd: number, cols: number, rows: number): void
export interface IConptyProcess {
  fd: number
  pty: number
  conin: string
  conout: string
}
export interface IConptyConnection {
  pid: number
}
export function conptyStartProcess(cols: number, rows: number, pipeName: string, conptyInheritCursor: boolean): IConptyProcess
export function conptyConnect(ptyId: number, cmdline: string, cwd: string, env: Record<string, string>, onexit: (...args: any[]) => any): IConptyConnection
export function conptyResize(ptyId: number, cols: number, rows: number): void
export function conptyKill(ptyId: number): void
export interface IWinptyProcess {
  pty: number
  fd: number
  conin: string
  conout: string
  pid: number
  innerPid: number
  innerPidHandle: number
}
export function winptyStartProcess(file: string, commandLine: string, env: Record<string, string>, cwd: string, cols: number, rows: number, debug: boolean): IWinptyProcess
export function winptyResize(pid: number, cols: number, rows: number): void
export function winptyKill(pid: number, innerPidHandle: number): void
export function winptyGetProcessList(pid: number): Array<number>
export function winptyGetExitCode(innerPidHandle: number): number
export function getConsoleProcessList(pid: number): Array<number>
/**
 * Bakes the version number into the binary so that it can be detected
 * if the binary version is not up to date with the library version
 */
export function version(): string
